services:
  envoy:
    image: envoyproxy/envoy:v1.20-latest
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "8080:8080"
    networks:
      - grpc-network

networks:
  grpc-network:
    driver: bridge