# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import main_pb2 as main__pb2


class MainAppStub(object):
    """MainApp Service for managing the application.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckConnection = channel.unary_unary(
                '/main_app.MainApp/CheckConnection',
                request_serializer=main__pb2.Empty.SerializeToString,
                response_deserializer=main__pb2.ConnectionStatus.FromString,
                )
        self.FetchConfigFiles = channel.unary_unary(
                '/main_app.MainApp/FetchConfigFiles',
                request_serializer=main__pb2.Empty.SerializeToString,
                response_deserializer=main__pb2.ConfigList.FromString,
                )
        self.UseConfigFile = channel.unary_unary(
                '/main_app.MainApp/UseConfigFile',
                request_serializer=main__pb2.ConfigName.SerializeToString,
                response_deserializer=main__pb2.Status.FromString,
                )


class MainAppServicer(object):
    """MainApp Service for managing the application.
    """

    def CheckConnection(self, request, context):
        """Check if the server is connected.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchConfigFiles(self, request, context):
        """Fetch all configuration file names.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UseConfigFile(self, request, context):
        """Use a configuration file to start a process.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MainAppServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckConnection,
                    request_deserializer=main__pb2.Empty.FromString,
                    response_serializer=main__pb2.ConnectionStatus.SerializeToString,
            ),
            'FetchConfigFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchConfigFiles,
                    request_deserializer=main__pb2.Empty.FromString,
                    response_serializer=main__pb2.ConfigList.SerializeToString,
            ),
            'UseConfigFile': grpc.unary_unary_rpc_method_handler(
                    servicer.UseConfigFile,
                    request_deserializer=main__pb2.ConfigName.FromString,
                    response_serializer=main__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'main_app.MainApp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MainApp(object):
    """MainApp Service for managing the application.
    """

    @staticmethod
    def CheckConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main_app.MainApp/CheckConnection',
            main__pb2.Empty.SerializeToString,
            main__pb2.ConnectionStatus.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FetchConfigFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main_app.MainApp/FetchConfigFiles',
            main__pb2.Empty.SerializeToString,
            main__pb2.ConfigList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UseConfigFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/main_app.MainApp/UseConfigFile',
            main__pb2.ConfigName.SerializeToString,
            main__pb2.Status.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
